import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("https://growmysub.com"),

  verification: {
    google: "Hq4XdXriSFiBdeg-sx6jsPDN8bVkkl3terWre7OrdhQ",
  },

  title: {
    default: "GrowMySub - Organic Subreddit Growth",
    template: "%s | GrowMySub",
  },

  description:
    "GrowMySub helps subreddit owners grow organic Reddit communities with subreddit promotion, content strategy, engagement planning, and community growth support.",

  keywords: [
    "Grow my sub",
    "Grow my sub fast",
    "Grow my sub organically",
    "Grow my sub online",
    "Grow my sub service",
    "Grow my sub platform",
    "Grow my sub company",
    "Grow my sub agency",
    "Best grow my sub service",
    "Professional grow my sub service",
    "Affordable grow my sub service",
    "Organic grow my sub service",
    "Grow my sub Reddit",
    "Grow my sub community",
    "Grow my sub members",
    "Grow my sub audience",
    "Grow my sub subscribers",
    "Grow my sub engagement",
    "Grow my sub naturally",
    "Grow my sub today",
    "Grow my subreddit",
    "Grow my subreddit fast",
    "Grow my subreddit organically",
    "Grow my subreddit service",
    "Grow my subreddit members",
    "Grow my subreddit audience",
    "Grow my subreddit community",
    "Grow subreddit",
    "Grow a subreddit",
    "Grow Reddit community",
    "Grow Reddit page",
    "Grow Reddit audience",
    "Grow Reddit members",
    "Grow subreddit fast",
    "Grow subreddit organically",
    "Grow subreddit naturally",
    "How to grow my sub",
    "How to grow my subreddit",
    "How to grow a subreddit",
    "How to grow subreddit fast",
    "How to grow Reddit community",
    "Best way to grow my sub",
    "Best way to grow my subreddit",
    "Best way to grow a subreddit",
    "Subreddit grow service",
    "Subreddit growth service",
    "Reddit growth service",
    "Organic subreddit growth",
    "Organic subreddit growth service",
    "Reddit promotion service",
    "Reddit marketing service",
    "Reddit community growth",
    "Reddit audience growth",
    "Reddit engagement service",
    "Reddit marketing agency",
    "Reddit growth agency",
    "Reddit community management",
    "Subreddit management service",
    "Reddit promotion company",
    "Increase subreddit members",
    "Increase subreddit subscribers",
    "Increase Reddit engagement",
    "Get more subreddit members",
    "Get more Reddit users",
    "Get more subreddit subscribers",
    "Get active subreddit members",
    "Build a Reddit community",
    "Build an active subreddit",
    "Reddit growth platform",
    "Reddit community building",
    "Reddit audience engagement",
    "Reddit organic marketing",
    "Organic Reddit promotion",
    "Organic Reddit growth",
    "Trusted subreddit growth",
    "Professional subreddit growth",
    "Best subreddit growth",
    "Best Reddit promotion",
    "Best Reddit marketing",
    "Best subreddit promotion",
    "Subreddit promotion",
    "Promote my subreddit",
    "Promote a subreddit",
    "Promote Reddit community",
    "Reddit community promotion",
    "Reddit user acquisition",
    "Scale my subreddit",
    "Scale Reddit community",
    "Reddit growth strategy",
    "Reddit growth experts",
    "Reddit growth solutions",
    "Reddit marketing experts",
    "Reddit community experts",
    "Reddit branding",
    "Reddit brand growth",
    "Grow niche subreddit",
    "Startup Reddit marketing",
    "SaaS Reddit marketing",
    "Business Reddit marketing",
    "Creator Reddit growth",
    "Reddit traffic growth",
    "Reddit visibility",
    "Improve subreddit engagement",
    "Increase Reddit visibility",
    "Make subreddit popular",
    "Reddit community success",
    "Viral subreddit growth",
    "Reddit growth tools",
    "Reddit community strategy",
    "Subreddit SEO",
    "Reddit SEO",
    "SEO for Reddit",
    "Reddit content strategy",
    "Reddit audience building",
    "Reddit member growth",
    "GrowMySub",
    "GrowMySub service",
    "GrowMySub platform",
    "GrowMySub Reddit growth",
    "Reddit community growth service",
    "Fast subreddit growth",
    "Safe subreddit growth",
    "Long term subreddit growth",
    "Reddit engagement strategy",
    "Reddit marketing solutions",
    "Reddit promotion experts",
    "Reddit growth consultant",
    "Subreddit marketing service",
    "Organic subreddit promotion",
    "How to grow a subreddit fast",
    "Best subreddit growth service",
    "How to promote a subreddit",
    "Subreddit promotion service",
    "How to get more subreddit members",
    "Grow my Reddit community",
    "Reddit branding service",
    "Reddit organic promotion",
    "How to make a subreddit popular",
    "Boost subreddit activity",
    "Increase subreddit engagement",
    "Get active Reddit members",
    "Reddit community marketing",
    "Buy subreddit management",
    "Scale your subreddit",
    "Trusted subreddit promotion",
    "Best Reddit promotion service",
    "Reddit community growth experts",
    "Subreddit growth platform",
    "Organic Reddit marketing service",
  ],

  robots: {
    index: true,
    follow: true,
  },

  alternates: {
    canonical: "https://growmysub.com",
  },

  openGraph: {
    title: "GrowMySub - Organic Subreddit Growth",
    description:
      "GrowMySub helps subreddit owners grow organic Reddit communities with subreddit promotion, content strategy, engagement planning, and community growth support.",
    type: "website",
    siteName: "GrowMySub",
    url: "https://growmysub.com",
  },

  twitter: {
    card: "summary",
    title: "GrowMySub - Organic Subreddit Growth",
    description:
      "GrowMySub helps subreddit owners grow organic Reddit communities with subreddit promotion, content strategy, engagement planning, and community growth support.",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
